# Generated by Django 6.0.1 on 2026-01-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0002_alter_actividad_descripcion_alter_actividad_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='documento_compromiso',
            field=models.FileField(blank=True, null=True, upload_to='documentos_compromiso/'),
        ),
    ]
