# Generated by Django 6.0.1 on 2026-02-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0003_alter_inscripcion_documento_compromiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=10),
        ),
    ]
