# Generated by Django 6.0.1 on 2026-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0006_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('CANCELADO', 'Cancelado')], default='INSCRITO', max_length=10),
        ),
    ]
